const mongoose =require("mongoose")
const Schema =mongoose.Schema;

// create user model
const blogSchema=new Schema({
    title:{
        type:String,
        required:true
    },
    author:{
        type:String,
        required:true
    },
    content:{
        type:String,
        required:true
    },
    introduction:{
        type:String,
    },
    category:{
        type:Schema.Types.ObjectId,
        ref:"categories"//与哪一个表关联
    },
    comment:[ 
        {
            content:{
                type:String,
                required:true
            },
            email:{
                type:String,
                required:true
            },
            replay:[
                {
                    content:{
                        type:String,
                        required:true
                    },
                    email:{
                        type:String,
                        required:true
                    },
                    date:{
                        type:Date,
                        default:Date.now
                    }
                }
            ],
            likes:{
                type:Number,
                default:0
            },
            dislikes:{
                type:Number,
                default:0
            },
            img:{
                type:String,
                default:"http://111.231.59.56:5000/images/vue.png"
            },
            date:{
                type:Date,
                default:Date.now
            }
              
        }
    ],
    likes:{
        type:Number,
        default:0
    },
    views:{
        type:Number,
        default:0
    },

    date:{
        type:Date,
        default:Date.now
    },
})
module.exports=blog=mongoose.model("blog",blogSchema)